## Services
google_analytics: 'UA-80279850-1'
duoshuo: duuyidong

## Meta
# rss: https://jysperm.me/atom.xml
favicon: /favicon.png
icon: /favicon.png
source_url: 'https://github.com/ADU-21/blog'
license:
  name: 'Amazon S3'
  url: 'https://aws.amazon.com/s3/'

## Menus
menus:
  '关于我': /about
  '日志列表': /list
  '读书': /booklist
  '电影': /movie
  '链接': /links
  '简历': /resume

right_menus:
  #'RSS': /atom.xml
  'Fork on Github':
    target: '_blank'
    href: 'https://github.com/ADU-21/blog'

## Banners && Widgets
banners:
  jade: |
    a(href='https://www.duyidong.com/awsSolutionsArchitect_AE.pdf') AWS认证方案解决架构师证书

widgets:
  -
    markdown: |
      杜屹东 生于 1993.12.16, 英文 ID Luke Du

      * 现就职于[ThoughtWorks](https://www.thoughtworks.com/)
      * 毕业于 [西华大学](http://www.xhu.edu.cn/) 计算机科学与技术
      * AWS认证方案解决架构师
      * 喜欢[史铁生](http://baike.baidu.com/view/39292.htm), [David Fincher](https://movie.douban.com/celebrity/1012521/) 和 [陈奕迅](http://baike.baidu.com/view/2556.htm)
      * 在剧组和影视公司工作过，对影视前后期工作略知一二，曾参与成龙大哥电影[《绝地逃亡》](https://movie.douban.com/subject/24529353/)制作
      * 曾骑行成都-拉萨，成都-北京，海南环岛

      目前专注于：

      * AWS - 云服务架构
      * DevOps - 文化组织变革
      * CI/CD - 持续集成与持续交付
      * Agile - 敏捷文化

  -
    tags: true

  -
    archives: true

  -
    copyright: true

